theme: jekyll-theme-minimal
title: "Left in the Shadow: Women's Fight for their Share of the Spotlight"
description: "Can Inclusivity and Success Coexist on Screen"
team: SAR team
names: Elsa Heitz and associates
show_downloads: true

kramdown:
  auto_ids: true
  auto_id_prefix: ''
  toc_levels: 1..3